# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.5"

[buildpack]
id       = "heroku/streaming-http-adapter-buildpack"
name     = "riff Streaming HTTP Adapter Buildpack"
version  = "{{.version}}"
homepage = "https://github.com/heroku/riff-streaming-http-adapter-buildpack" # Uncomment this when heroku fork is public

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[metadata.dependencies]]
id      = "heroku/streaming-http-adapter-buildpack"
name    = "Heroku riff Streaming HTTP Adapter"
version = "0.5.4"
uri     = "https://heroku-build-artifacts.s3.us-east-2.amazonaws.com/streaming-http-adapter-buildpack/streaming-http-adapter-linux-amd64-latest.tgz"
sha256  = "d408dcee6beaf5edb76ce8cae369e7cd2b6f374248961c9cabcddf37ff935a28"
stacks  = [ "heroku-18", "heroku-20", "io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/heroku/riff-streaming-http-adapter-buildpack/blob/main/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/detect",
  "bin/main",
  "buildpack.toml",
]
